# SPDX-License-Identifier: MIT
# Copyright (c) 2026 straysheep-dev
# Assisted-by: claude-sonnet-5

# Override file for Caddy, so it depends on Tailscale.
# /etc/systemd/system/caddy.service.d/override.conf

[Unit]
After=tailscaled.service
Wants=tailscaled.service

[Service]
Restart=on-failure
RestartSec=2